name: Frontend CI/CD
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    name: Build, Test & Deploy Angular App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: npm
      
      - name: Install Angular dependencies
        run: npm ci
      
      - name: Lint Angular code
        run: npm run lint
      
      - name: Build Angular App
        run: npm run build --if-present
      
      # - name: Run Angular tests
      #   run: npm test -- --watch=false --browsers=ChromeHeadless
      
      - name: Deploy to Firebase
        # Only deploy on push to master, not on pull requests
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOUR_PROJECT_ID }}'
          channelId: live
          projectId: angular-chatgpt